### ISSUE TITLE
Transparency no longer working

### ISSUE THREAD

**Issue by mpicard** [DFgraphics/Spacefox#6]
![screenshot_20180720_085813](https://user-images.githubusercontent.com/7460934/42990632-191ab05a-8bfb-11e8-99f6-e722b8cdd015.png)

Seems like transparency is no longer working? Is there something I have to do to enable that?

**Comment by claireanlage** [comment]
Closing this as it's pretty old and probably a problem with TWBT or something similar. If there was a problem with the png file itself, it probably has been updated a dozen times by now.

I checked the current png and it's a 32bit png with proper alpha channel transparency and displays fine in DF.
Feel free to reopen if you can reproduce the problem.
